# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/Codes/Digital-circuit-course/Calculator/Calculator.runs/synth_1/.Xil/Vivado-12700-Monsoon-PC/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include d:/Codes/Digital-circuit-course/Calculator/Calculator.srcs/sources_1/ip/VGA_clk_1920_1080_60Hz D:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      rt::read_verilog -include d:/Codes/Digital-circuit-course/Calculator/Calculator.srcs/sources_1/ip/VGA_clk_1920_1080_60Hz {
      D:/Codes/Digital-circuit-course/Calculator/Calculator.runs/synth_1/.Xil/Vivado-12700-Monsoon-PC/realtime/VGA_clk_1920_1080_60Hz_stub.v
      D:/Codes/Digital-circuit-course/Calculator/Calculator.srcs/sources_1/new/Controller.v
      D:/Codes/Digital-circuit-course/Calculator/Calculator.srcs/sources_1/new/Execute.v
      D:/Codes/Digital-circuit-course/Calculator/Calculator.srcs/sources_1/new/Font.v
      D:/Codes/Digital-circuit-course/Calculator/Calculator.srcs/sources_1/new/Keyboard.v
      D:/Codes/Digital-circuit-course/Calculator/Calculator.srcs/sources_1/new/Number_to_String.v
      D:/Codes/Digital-circuit-course/Calculator/Calculator.srcs/sources_1/new/Stack.v
      D:/Codes/Digital-circuit-course/Calculator/Calculator.srcs/sources_1/new/String_parser.v
      D:/Codes/Digital-circuit-course/Calculator/Calculator.srcs/sources_1/new/String_to_Number.v
      D:/Codes/Digital-circuit-course/Calculator/Calculator.srcs/sources_1/new/VGA.v
      D:/Codes/Digital-circuit-course/Calculator/Calculator.srcs/sources_1/new/display.v
      D:/Codes/Digital-circuit-course/Calculator/Calculator.srcs/sources_1/new/top.v
    }
      rt::read_vhdl -lib xpm D:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList D:/Codes/Digital-circuit-course/Calculator/Calculator.runs/synth_1/.Xil/Vivado-12700-Monsoon-PC/realtime/top_synth.xdc
    rt::sdcChecksum
    set rt::top top
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {D:/Codes/Digital-circuit-course/Calculator/Calculator.cache/wt}
    rt::set_parameter enableSplitFlowPath "D:/Codes/Digital-circuit-course/Calculator/Calculator.runs/synth_1/.Xil/Vivado-12700-Monsoon-PC/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
