set_property SRC_FILE_INFO {cfile:d:/Codes/Digital-circuit-course/Calculator/Calculator.srcs/sources_1/ip/VGA_clk_1920_1080_60Hz/VGA_clk_1920_1080_60Hz/VGA_clk_1920_1080_60Hz_in_context.xdc rfile:../../../../../Calculator.srcs/sources_1/ip/VGA_clk_1920_1080_60Hz/VGA_clk_1920_1080_60Hz/VGA_clk_1920_1080_60Hz_in_context.xdc id:1 order:EARLY scoped_inst:monitor/vga/vgaclk_1920_1080_60hz} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/rayomnd/Desktop/数字电路实验/Nexys4DDR_Master.xdc rfile:C:/Users/rayomnd/Desktop/数字电路实验/Nexys4DDR_Master.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name CLK100MHZ [get_ports CLK100MHZ]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name monitor/vga/vgaclk_1920_1080_60hz/clk_out1 -source [get_ports CLK100MHZ] -edges {1 2 3} -edge_shift {0.000 -1.633 -3.266} [get_pins monitor/vga/vgaclk_1920_1080_60hz/clk_out1]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports CLK100MHZ]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports CLK100MHZ]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells monitor/vga/vgaclk_1920_1080_60hz]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells monitor/vga/vgaclk_1920_1080_60hz]
