# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/数字电路实验/Nexys4DDR_Master.xdc

# IP: ip/c_counter_binary_4/c_counter_binary_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_4 || ORIG_REF_NAME==c_counter_binary_4} -quiet] -quiet

# IP: ip/c_counter_binary_9_1/c_counter_binary_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_9 || ORIG_REF_NAME==c_counter_binary_9} -quiet] -quiet
