# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Codes/Digital-circuit-course/LC3/LC3.srcs/sources_1/ip/Block_Memory/Block_Memory.xci
# IP: The module: 'Block_Memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Codes/Digital-circuit-course/LC3/LC3.srcs/sources_1/ip/Block_Memory/Block_Memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Memory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Codes/Digital-circuit-course/LC3/LC3.srcs/sources_1/ip/Block_Memory/Block_Memory.xci
# IP: The module: 'Block_Memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Codes/Digital-circuit-course/LC3/LC3.srcs/sources_1/ip/Block_Memory/Block_Memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
