# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Codes/Digital-circuit-course/Calculator/Calculator.srcs/sources_1/ip/VGA_clk_1920_1080_60Hz/VGA_clk_1920_1080_60Hz.xci
# IP: The module: 'VGA_clk_1920_1080_60Hz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Codes/Digital-circuit-course/Calculator/Calculator.srcs/sources_1/ip/VGA_clk_1920_1080_60Hz/VGA_clk_1920_1080_60Hz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_clk_1920_1080_60Hz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Codes/Digital-circuit-course/Calculator/Calculator.srcs/sources_1/ip/VGA_clk_1920_1080_60Hz/VGA_clk_1920_1080_60Hz.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_clk_1920_1080_60Hz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Codes/Digital-circuit-course/Calculator/Calculator.srcs/sources_1/ip/VGA_clk_1920_1080_60Hz/VGA_clk_1920_1080_60Hz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_clk_1920_1080_60Hz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Codes/Digital-circuit-course/Calculator/Calculator.srcs/sources_1/ip/VGA_clk_1920_1080_60Hz/VGA_clk_1920_1080_60Hz.xci
# IP: The module: 'VGA_clk_1920_1080_60Hz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Codes/Digital-circuit-course/Calculator/Calculator.srcs/sources_1/ip/VGA_clk_1920_1080_60Hz/VGA_clk_1920_1080_60Hz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_clk_1920_1080_60Hz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Codes/Digital-circuit-course/Calculator/Calculator.srcs/sources_1/ip/VGA_clk_1920_1080_60Hz/VGA_clk_1920_1080_60Hz.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_clk_1920_1080_60Hz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Codes/Digital-circuit-course/Calculator/Calculator.srcs/sources_1/ip/VGA_clk_1920_1080_60Hz/VGA_clk_1920_1080_60Hz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_clk_1920_1080_60Hz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
